swagger: '2.0'
basePath: /admin
schemes:
  - http
  - https
info:
  title: Central Ledger Admin API Documentation - Updated to include positions only
  version: 2.4.0-snapshot
#host: 'localhost:3001'
tags: []

paths:
  /participants/positions:
    get:
      summary: List positions for all Participants
      operationId: getPositions
      tags:
        - positions
      responses:
        default:
          schema:
            $ref: "#/definitions/PositionsGetResponse"
          description: Successful
          x-examples:
            "application/json":
              { 
                snapshotAt: “2018-07-07T08:38:08.699-04:00”,
                positions:
                  [
                    {
                      participantId: dfsp1,
                      participantPositions: 
                        [
                          {
                            currentPosition:
                            {
                              currency: "USD",
                              value: 20000,
                              reservedValue: 2000,
                              lastUpdated: “2018-07-05T08:38:08.699-04:00”
                            }
                          },
                          {
                            currentPosition:
                            {
                              currency: "INR",
                              value: 5000000,
                              reservedValue: 10000,
                              lastUpdated: “2018-07-06T08:38:08.699-04:00”
                            }
                          }
                        ]
                    },
                    {
                      participantId: dfsp2,
                      participantPositions: 
                        [
                          {
                            currentPosition:
                            {
                              currency: "USD",
                              value: 5000000,
                              reservedValue: 50000,
                              lastUpdated: “2018-07-05T08:38:08.699-04:00”
                            }
                          },
                          {
                            currentPosition:
                            {
                              currency: "GBP",
                              value: 20000000,
                              reservedValue: 2000,
                              lastUpdated: “2018-07-06T08:38:08.699-04:00”
                            }
                          }
                        ]
                    }
                  ]
              }
  /participants/{name}/positions:
    get:
      summary: Query position for a Participant
      operationId: getPositionsName
      parameters:
        - type: string
          description: Participant Name required
          name: name
          in: path
          required: true
      tags:
        - positions
      responses:
        default:
          schema:
            $ref: "#/definitions/PositionsNameGetResponse"
          description: Successful
          x-examples:
            "application/json":
              { 
                participantId: dfsp2,
                respondedAt: “2018-07-05T08:38:08.699-04:00”,
                participantPositions: 
                  [
                    {
                      currentPosition:
                      {
                        currency: "USD",
                        value: 20000,
                        reservedValue: 2000,
                        lastUpdated: “2018-07-05T08:38:08.699-04:00”
                      }
                    },
                    {
                      currentPosition:
                      {
                        currency: "ZAR",
                        value: 100000,
                        reservedValue: 1000,
                        lastUpdated: “2018-07-06T08:38:08.699-04:00”
                      }
                    }
                  ]
              }

definitions:
  Amount:
    title: Amount
    type: string
    pattern: ^([0]|([1-9][0-9]{0,17}))([.][0-9]{0,3}[1-9])?$
    description: The API data type Amount is a JSON String in a canonical format that is restricted by a regular expression for interoperability reasons. This pattern does not allow any trailing zeroes at all, but allows an amount without a minor currency unit. It also only allows four digits in the minor currency unit; a negative value is not allowed. Using more than 18 digits in the major currency unit is not allowed.
  Currency:
    title: CurrencyEnum
    description: The currency codes defined in ISO 4217 as three-letter alphabetic codes are used as the standard naming representation for currencies.
    type: string
    minLength: 3
    maxLength: 3
    enum:
    - AED
    - AFN
    - ALL
    - AMD
    - ANG
    - AOA
    - ARS
    - AUD
    - AWG
    - AZN
    - BAM
    - BBD
    - BDT
    - BGN
    - BHD
    - BIF
    - BMD
    - BND
    - BOB
    - BRL
    - BSD
    - BTN
    - BWP
    - BYN
    - BZD
    - CAD
    - CDF
    - CHF
    - CLP
    - CNY
    - COP
    - CRC
    - CUC
    - CUP
    - CVE
    - CZK
    - DJF
    - DKK
    - DOP
    - DZD
    - EGP
    - ERN
    - ETB
    - EUR
    - FJD
    - FKP
    - GBP
    - GEL
    - GGP
    - GHS
    - GIP
    - GMD
    - GNF
    - GTQ
    - GYD
    - HKD
    - HNL
    - HRK
    - HTG
    - HUF
    - IDR
    - ILS
    - IMP
    - INR
    - IQD
    - IRR
    - ISK
    - JEP
    - JMD
    - JOD
    - JPY
    - KES
    - KGS
    - KHR
    - KMF
    - KPW
    - KRW
    - KWD
    - KYD
    - KZT
    - LAK
    - LBP
    - LKR
    - LRD
    - LSL
    - LYD
    - MAD
    - MDL
    - MGA
    - MKD
    - MMK
    - MNT
    - MOP
    - MRO
    - MUR
    - MVR
    - MWK
    - MXN
    - MYR
    - MZN
    - NAD
    - NGN
    - NIO
    - NOK
    - NPR
    - NZD
    - OMR
    - PAB
    - PEN
    - PGK
    - PHP
    - PKR
    - PLN
    - PYG
    - QAR
    - RON
    - RSD
    - RUB
    - RWF
    - SAR
    - SBD
    - SCR
    - SDG
    - SEK
    - SGD
    - SHP
    - SLL
    - SOS
    - SPL
    - SRD
    - STD
    - SVC
    - SYP
    - SZL
    - THB
    - TJS
    - TMT
    - TND
    - TOP
    - TRY
    - TTD
    - TVD
    - TWD
    - TZS
    - UAH
    - UGX
    - USD
    - UYU
    - UZS
    - VEF
    - VND
    - VUV
    - WST
    - XAF
    - XCD
    - XDR
    - XOF
    - XPF
    - YER
    - ZAR
    - ZMW
    - ZWD
  DateTime:
    title: DateTime
    type: string
    pattern: ^(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:(\.\d{3}))(?:Z|[+-][01]\d:[0-5]\d)$
    description: The API data type DateTime is a JSON String in a lexical format that is restricted by a regular expression for interoperability reasons.
      The format is according to ISO 8601, expressed in a combined date, time and time zone format. A more readable version of the format is yyyy-MM-ddTHH:mm:ss.SSS[-HH:MM]. Examples -  "2016-05-24T08:38:08.699-04:00", "2016-05-24T08:38:08.699Z" (where Z indicates Zulu time zone, same as UTC).
  ParticipantId:
    title: ParticipantId
    type: string
    minLength: 1
    maxLength: 32
    description: FSP or Participant identifier
  SinglePosition:
    title: SinglePosition
    type: object
    description: Data model for the complex type SinglePosition
    properties:
      currency:
        $ref: '#/definitions/Currency'
        description: Currency of the amount
      value:
        $ref: '#/definitions/Amount'
        description: Value of position
      reservedValue:
        $ref: '#/definitions/Amount'
        description: ReservedValue of position
      lastUpdated:
        $ref: "#/definitions/DateTime"
        description: Time when this position values were last updated
    required:
    - currency
    - value
    - reservedValue
    - lastUpdated
  PositionsNameGetResponse:
    type: object
    properties:
      participantId:
        $ref: "#/definitions/ParticipantId"
      respondedAt:
        $ref: "#/definitions/DateTime"
      participantPositions:
        type: array
        minItems: 1
        maxItems: 200
        items:
          $ref: "#/definitions/SinglePosition"
    required:
      - participantPositions
      - participantId
      - respondedAt
  SingleFSPPosition:
    type: object
    properties:
      participantId:
        $ref: "#/definitions/ParticipantId"
      participantPositions:
        type: array
        minItems: 1
        maxItems: 200
        items:
          $ref: "#/definitions/SinglePosition"
    required:
      - participantPositions
      - participantId
  PositionsGetResponse:
    type: object
    properties:
      snapshotAt:
        $ref: "#/definitions/DateTime"
      positions:
        type: array
        minItems: 1
        maxItems: 250
        items:
          $ref: "#/definitions/SingleFSPPosition"
    required:
      - snapshotAt
      - positions